### ISSUE TITLE
When will @openzeppelin/contracts@5.0.2 be supported?

### ISSUE THREAD

**Issue by time-holder** [matter-labs/hardhat-zksync#1019]
It looks like contract deployment doesn't seem to support `@openzeppelin/contracts@5.0.2` and `@openzeppelin/contracts-upgradeable@5.0.2`. Is there any plan to upgrade?

My contract is written based on version 5.0.2. It compiles successfully, but the following error occurs during deployment:
<img width="963" alt="image" src="https://github.com/matter-labs/hardhat-zksync/assets/139603969/2f79be0a-b7e3-4aed-80d8-2eee01ef71ed">

I found that all the packages under `@matterlabs/hardhat-zksync-*` depend on @openzeppelin version v4.9.2. This could be the reason for the failure.

**Comment by nikola-bozin-txfusion** [comment]
Hello @time-holder The primary reason we haven't updated this feature in our plugin yet is due to compatibility issues that arise when it's used alongside the @matterlabs/zksync-contracts package. This package relies on outdated versions of the @openzeppelin contracts, which can cause errors.

We are optimistic that this issue will be resolved soon.

**Comment by logan272** [comment]
Any update when will @openzeppelin/contracts@v5 be supported?

**Comment by kiriyaga-txfusion** [comment]
We are still waiting for the ML team to update the OpenZeppelin dependencies used in the @matterlabs/zksync-contracts, which may cause conflicts.
