### ISSUE TITLE
Update to ethers v6

### ISSUE THREAD

**Issue by fvictorio** [matter-labs/hardhat-zksync#311]
Hi, we recently updated all of our official plugins to rely on ethers v6. It would be great if these plugins would do the same, because that would enable templates like [this one](https://github.com/pcaversaccio/hardhat-project-template-ts) to completely upgrade to these new versions.

From what I can tell, the necessary changes are:
- `hardhat-zksync-deploy` should update its peer dependency on ethers to `^6.0.0`
- That change requires `zksync-web3` to also upgrade its peer dependency (this will probably be the biggest change)
- `hardaht-zksync-verify` should change its dependency on `@nomiclabs/hardhat-etherscan` to `@nomicfoundation/hardhat-verify`. This is not strictly related to ethers v6, but our new Toolbox uses this new plugin. This will require some changes on the subtasks you are using/overriding.

In all cases, I'm happy to help in any way I can.

Thanks!

**Comment by pcaversaccio** [comment]
@FilipTxFusion any update on when this upgrade is planned? Would appreciate if it could happen sooner than later since the current bottleneck is only on the zksync that prevents bumping ethers.

**Comment by vladikopl01** [comment]
Are there any updates on this issue? Should I wait for ethers-v6 update or it will not come soon? Thanks

**Comment by FilipTxFusion** [comment]
Hi @fvictorio, thanks for those suggestions!
We are aware of it, but are currently blocked by a couple of internal things regarding upgrading all packages to support ethers v6. Regarding the change of the hardhat-zksync-verify plugin dependency from @nomiclabs/hardhat-etherscan to @nomicfoundation/hardhat-verify, we released a new version of the verify plugin - 0.2.0 - that implements this change.

@pcaversaccio, @vladikopl01 I can't give you the exact timeline of the upgrade because of the blockers we have, but we are aware of its impact on other projects.
I will push for the prioritization of it asap.

**Comment by pcaversaccio** [comment]
@FilipTxFusion thanks for the heads-up. The upgrade `@nomicfoundation/hardhat-verify` doesn't help much if you use `@nomicfoundation/hardhat-toolbox` since either you upgrade to `ethers` `v6` as well or you use the old toolbox which still requires the `@nomiclabs/hardhat-etherscan` deps.

**Comment by FilipTxFusion** [comment]
Yes we are aware of this. The transition to `ethers` `v6` will happen as soon as possible.

**Comment by ZumZoom** [comment]
Hey guys. Do you have any updates on that issue?

**Comment by kiriyaga-txfusion** [comment]
Hello, all plugins from version 1.0.0 are updated to support ethers v6.
