### ISSUE TITLE
how to make cache-zk work?

### ISSUE THREAD

**Issue by GopherJ** [matter-labs/hardhat-zksync#312]
I have the feeling that cache-zk is not working, my branch is at: https://github.com/para-space/paraspace-core/blob/feat/zksync-era/hardhat.config.ts

when I compile, I always need to add `--no-compile` flag, otherwise it always compiles more than 500 contracts, which is super super slow (> 10 minutes)

also before of [this issue](https://github.com/NomicFoundation/hardhat/issues/4029), when I verify my contracts it automatically recompiles because `--no-compile` doesn't work in task, these two things cause it hard to verify contracts as it always recompiles

**Comment by mpopovac-txfusion** [comment]
Hey @GopherJ, we're currently working on the fix for the cache-zk when compiling, this will be released probably next week. 
Also, as mentioned in the issue you linked, some tasks don't have --no-compile option.
Verify task must run the compile task since it is one of the required steps to compare bytecode in the verification process.

**Comment by GopherJ** [comment]
with     "@matterlabs/hardhat-zksync-solc": "^0.4.0" seems the cache is now working except it's not auto-generating typechain types, not sure if it's hardhat issue or my wrong usage

**Comment by sebastiantf** [comment]
I am using "@matterlabs/hardhat-zksync-solc": "^0.4.0", but the cache doesnt seem to be used. Always taking very long for compilation
