### ISSUE TITLE
no compile option for @matterlabs/hardhat-zksync-verify

### ISSUE THREAD

**Issue by stnong** [matter-labs/hardhat-zksync#805]
#### 💥 Plugin name

@matterlabs/hardhat-zksync-verify

#### 📝 Description

add an optional no-compile flag so the plugin will not compile all contracts

#### 🤔 Rationale

Everytime I want to verify a contract the plugin will compile the whole project even if compilation is not necessary. This takes a lot of time for big projects or if you want to compile multiple contracts in a row.

#### 🖼️ Mockups/Examples

```
const verificationId = await hre.run("verify:verify", {
  address: contractAddress,
  contract: contractFullyQualifedName,
  constructorArguments: [...],
  noCompile: true
});
```

and

```
yarn hardhat verify --network <network> <contract address> --contract <fully qualified name> --noCompile
```

**Comment by kiriyaga-txfusion** [comment]
Hey @stnong ,

I wanted to let you know that the plugin already has a feature implemented for contract verification. You can use it either from the command line or programmatically. It's not documented because we're cautious about encouraging its use without proper understanding.

Here's how you can use it:

**Command line:**
`yarn hardhat verify --no-compile [contract-address] [constructor-args]`

**Programmatic usage (as you mentioned):**
```
const verificationId = await hre.run("verify:verify", {
  // Configuration options here
  noCompile: true
});
```

Just a heads up, the _--no-compile_ flag indicates that the verification process won't include compilation steps.

However, it's important to understand what you're doing and why before using this feature. While there are safety mechanisms in place, it's always good to proceed with caution when dealing with contract verification.
